version: "3"

services:
  apibackend:
    image: api_dockerized
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: ./migratedb.sh
    ports:
      - 8000:8000
    environment:
    #env vars for django db and super user
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=superuserpassword                                    
      - DB_URL=dbproj1aws.cnprtk3bvxit.eu-west-2.rds.amazonaws.com  
