version: "3"

services:
  apibackend:
    image: api_dockerized
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: ./migratedb.sh
    ports:
      - 8000:8000
    environment:
    #env vars for django db and super user
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=superuserpassword                                    
###
###
###
      - DB_URL=${var.db_instance_address}
      - DB_USER=${var.db_instance_username}
      - DB_NAME=${var.db_name}
      - DB_PORT=${var.db_instance_port}
      - DB_PASSWORD=${var.db_instance_password}
